title: "Nyala HexaQuad"
email: mauro.borrageiro7@gmail.com
remote_theme: just-the-docs/just-the-docs
search_enabled: true

github_username: MBorrageiro

open_new_tab: true
aux_links_new_tab: true

aux_links:
  "HexaQuad on GitHub":
  - "https://github.com/landrs-toolkit/LANDRs-Science-Drone"

logo: "/Images/HexaQuadLogo.svg"

back_to_top: true
back_to_top_text: "Back to top"


footer_content: "Copyright &copy; LANDRs 2022. Distributed by an <a href=\"https://github.com/landrs-toolkit/LANDRs-Science-Drone/blob/main/LicenseInformation/cern_ohl_p_v2.pdf">CERN-OHL-P v2 permissive license."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
